### ISSUE TITLE
Uncaught Error: Module did not self-register

### ISSUE THREAD

**Issue by lenart** [aki77/atom-autocomplete-ctags#19]
Here's an error I've been receiving lately on Atom 1.10.2, macOS sierra (beta).
1. Open a haml/slim file in atom
2. type some characters and the error appears

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12
**Thrown From**: [autocomplete-ctags](https://github.com/aki77/atom-autocomplete-ctags) package, v0.4.1
### Stack Trace

Uncaught Error: Module did not self-register.

```
At ELECTRON_ASAR.js:158

Error: Module did not self-register.
    at Error (native)
    at process.module.(anonymous function) (ELECTRON_ASAR.js:158:20)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:440:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/ctags/lib/ctags.js:4:10)
    at Object.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/ctags/lib/ctags.js:60:4)
    at Module._compile (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at CtagsProvider.module.exports.CtagsProvider.findTags (/Users/lenart/.atom/packages/autocomplete-ctags/lib/ctags-provider.coffee:78:14)
    at /Users/lenart/.atom/packages/autocomplete-ctags/lib/ctags-provider.coffee:60:8
    at Array.map (native)
    at CtagsProvider.module.exports.CtagsProvider.getSuggestions (/Users/lenart/.atom/packages/autocomplete-ctags/lib/ctags-provider.coffee:59:27)
    at /opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:325:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:304:17)
    at AutocompleteManager.getSuggestionsFromProviders (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:291:19)
    at /opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```
### Commands

```
     -0:04.4.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:04.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:04.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:04.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:04.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -0:02.8.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:02.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:01.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:01.8.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:01.8.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:01.8.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:01.1.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:01.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:00.8.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:00.8.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:00.8.0 editor:indent (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "git-blame-plus",
      "file-types",
      "synced-sidebar",
      "linter-csslint",
      "symbols-view",
      "emmet",
      "vim-mode",
      "blame",
      "linter-reek",
      "linter-codeclimate",
      "linter-rails-best-practices",
      "linter-htmlhint"
    ],
    "excludeVcsIgnoredPaths": false,
    "ignoredNames": [
      ".git",
      ".DS_Store",
      "Thumbs.db",
      ".tags*",
      ".vagrant",
      ".bundle",
      ".idea",
      "tmp/",
      "log/*.log"
    ],
    "packagesWithKeymapsDisabled": [
      "vim-mode"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  },
  "autocomplete-ctags": {}
}
```
### Installed Packages

``` coffee
# User
afterglow-monokai-syntax, v1.3.4 (inactive)
atom-beautify, v0.29.11 (inactive)
atom-ctags, v5.0.0 (active)
atom-everydayrails-rspec, v0.4.0 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-ui, v1.3.6 (active)
atom-prettify, v0.1.3 (inactive)
autocomplete, v0.47.0 (inactive)
autocomplete-ctags, v0.4.1 (active)
autocomplete-ruby, v0.1.0 (active)
autocomplete-sass, v0.1.0 (active)
capybara-snippets, v0.2.0 (active)
change-case, v0.6.3 (active)
coffee-navigator, v0.0.18 (active)
color-picker, v2.2.2 (active)
dash, v1.6.2 (inactive)
emmet, v2.4.3 (inactive)
file-icons, v1.7.19 (active)
fold-comments, v0.6.0 (inactive)
git-blame, v0.4.11 (inactive)
git-history, v3.2.0 (inactive)
git-plus, v5.17.0 (inactive)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
html2haml, v0.10.0 (active)
html2slim, v0.4.0 (inactive)
jsonlint, v1.1.4 (active)
language-ejs, v0.2.0 (active)
language-haml, v0.24.0 (active)
language-rspec, v0.5.0 (active)
language-slim, v0.5.0 (active)
line-ending-converter, v1.3.2 (active)
linter, v1.11.16 (active)
linter-codeclimate, v0.1.2 (inactive)
linter-csslint, v1.3.2 (inactive)
linter-haml, v1.2.1 (active)
linter-htmlhint, v1.3.0 (inactive)
linter-jshint, v2.1.0 (active)
linter-jsonlint, v1.3.0 (active)
linter-rails-best-practices, v0.2.2 (inactive)
linter-rubocop, v0.4.7 (active)
linter-scss-lint, v3.0.4 (active)
linter-slim, v1.0.0 (active)
merge-conflicts, v1.4.4 (active)
php-twig, v4.0.0 (active)
pigments, v0.34.0 (active)
pretty-json, v1.6.0 (active)
rails-partials, v0.9.2 (inactive)
rails-rspec, v0.3.2 (inactive)
rails-snippets, v2.8.0 (inactive)
rails-transporter, v1.6.5 (inactive)
react, v0.16.0 (active)
reveal-active-file-context, v0.2.0 (active)
rspec-snippets, v0.4.0 (active)
rubocop-auto-correct, v1.5.1 (inactive)
ruby-block, v0.3.5 (active)
ruby-slim, v0.2.0 (active)
ruby-test, v0.9.17 (inactive)
script, v3.9.0 (inactive)
Sublime-Style-Column-Selection, v1.7.2 (active)
svg-preview, v0.9.0 (active)
swackets, v0.11.0 (active)
synced-sidebar, v0.4.3 (inactive)
toggle-quotes, v1.0.0 (inactive)
underscorejs-snippets, v0.2.2 (active)
wakatime, v6.0.10 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by AdamMarkowski** [comment]
The same happens at my editor - mac os el capitan.

**Comment by stjernstrom** [comment]
Same for me since last update  - mac os el capitan.

**Comment by srinathv** [comment]
same for me since last updated - mac os sierra

**Comment by nandak522** [comment]
same for me - ubuntu 14.04

**Comment by jellybob** [comment]
Also here, running on Ubuntu 15.10 (yes, I know, its not an LTS _or_ a recent release). I'm currently seeing it while editing some Elixir source, but not sure if the actual file is relevant.

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Ubuntu 15.10
**Thrown From**: [autocomplete-ctags](https://github.com/aki77/atom-autocomplete-ctags) package, v0.4.1

### Stack Trace

Uncaught Error: Module did not self-register.

```
At ELECTRON_ASAR.js:158

Error: Module did not self-register.
    at Error (native)
    at process.module.(anonymous function) (ELECTRON_ASAR.js:158:20)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:440:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/opt/atom/resources/app.asar/node_modules/ctags/lib/ctags.js:4:10)
    at Object.<anonymous> (/opt/atom/resources/app.asar/node_modules/ctags/lib/ctags.js:60:4)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at CtagsProvider.module.exports.CtagsProvider.findTags (/home/jon/.atom/packages/autocomplete-ctags/lib/ctags-provider.coffee:78:14)
    at /home/jon/.atom/packages/autocomplete-ctags/lib/ctags-provider.coffee:60:8
    at Array.map (native)
    at CtagsProvider.module.exports.CtagsProvider.getSuggestions (/home/jon/.atom/packages/autocomplete-ctags/lib/ctags-provider.coffee:59:27)
    at /opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:325:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:304:17)
    at AutocompleteManager.getSuggestionsFromProviders (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:291:19)
    at /opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
  2x -1:05.5.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -1:04.9.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:03.7.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:03.5.0 vim-mode:move-to-last-character-of-line (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:03.4.0 vim-mode:delete-right (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -1:03.1.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -1:02.6.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -1:02.1.0 vim-mode:insert-after (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -1:01.8.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:53.1.0 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:52.8.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:46.1.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:44.3.0 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:43.3.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:36.8.0 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -0:36 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "underline-trailing-whitespace",
      "linter-eslint",
      "symbols-view"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "atom-solarized-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
.bin, vundefined (inactive)
angularjs, v0.3.5 (active)
atom-ctags, v5.0.0 (active)
atom-elixir, v0.2.1 (active)
atom-pair, v2.0.10 (active)
atom-solarized-dark-ui, v0.25.0 (active)
autocomplete-ctags, v0.4.1 (active)
autocomplete-elixir, v1.5.14 (active)
build-elixir, v0.6.0 (active)
dockerletion, v0.2.0 (active)
emmet, v2.4.3 (active)
git-plus, v5.18.0 (active)
language-docker, v1.1.7 (active)
language-elixir, v0.16.0 (active)
language-javascript-jsx, v0.3.7 (active)
language-nginx, v0.6.2 (active)
language-terraform, v0.7.4 (active)
linter, v1.11.18 (active)
linter-eslint, v8.0.0 (inactive)
linter-rubocop, v0.5.0 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.6 (active)
pigments, v0.37.0 (active)
ruby-block, v0.3.5 (active)
ruby-block-converter, v3.5.0 (active)
ruby-test, v0.9.17 (inactive)
sort-lines, v0.14.0 (inactive)
tab-switcher, v1.5.4 (active)
trailing-spaces, v0.3.2 (active)
vim-mode, v0.65.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (active)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by zdraganov** [comment]
Same on Mac Sierra

**Comment by lenart** [comment]
I've been playing around and run `npm install -g node-gyp` and then reinstalled the autocomplete-ctags package:

```
apm uninstall autocomplete-ctags
apm install autocomplete-ctags
```

I've also rebuilt the node modules from `/usr/local/lib/node_modules` (run `npm rebuild`). Not sure what actually fixed it but I'm not getting the error since.

**Comment by chenasraf** [comment]
@lenart Did you do anything else? This didn't seem to work for me. Maybe something more did the job.

**Comment by lenart** [comment]
@chenasraf unfortunately I don't remember doing anything else for getting this fixed.
