### ISSUE TITLE
Uncaught Error: Cannot find module '../build/Release/ctags.node'

### ISSUE THREAD

**Issue by sethyoung** [aki77/atom-autocomplete-ctags#22]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [autocomplete-ctags](https://github.com/aki77/atom-autocomplete-ctags) package 0.4.1

### Stack Trace

Uncaught Error: Cannot find module '../build/Release/ctags.node'

```
At C:\Users\seth\AppData\Local\atom\app-1.15.0\resources\app.asar\src\module-cache.js:379

Error: Cannot find module '../build/Release/ctags.node'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.15.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-autocomplete-ctags/node_modules/ctags/lib/ctags.js:4:10)
    at /packages/atom-autocomplete-ctags/node_modules/ctags/lib/ctags.js:60:4)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at CtagsProvider.module.exports.CtagsProvider.findTags (/packages/atom-autocomplete-ctags/lib/ctags-provider.coffee:78:14)
    at /packages/atom-autocomplete-ctags/lib/ctags-provider.coffee:60:8
    at Array.map (native)
    at CtagsProvider.module.exports.CtagsProvider.getSuggestions (/packages/atom-autocomplete-ctags/lib/ctags-provider.coffee:59:27)
    at /app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:333:54
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:309:17)
    at AutocompleteManager.findSuggestions (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:298:19)
```

### Commands

```
     -7:59.1.0 settings-view:open (input.hidden-input)
  8x -4:57.5.0 core:undo (input.hidden-input)
 17x -4:51.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.3.0 
autocomplete-ctags 0.4.1 
atom-autocomplete-php 0.22.0 
autoprefixer 3.6.1 
atom-beautify 0.29.17 
atom-ctags 5.0.0 
tree-view-git-status 1.3.1 
autocomplete-paths 1.0.5 
color-picker 2.2.5 
csscomb 0.3.1 
docblockr 0.9.1 
emmet 2.4.3 
file-icons 2.0.17 
git-log 0.4.1 
git-plus 7.3.3 
html-to-string 0.2.3 
merge-conflicts 1.4.4 
minimap 4.26.8 
project-manager 3.3.3 
tree-view-finder 0.2.1 
```

**Comment by LG5A-104** [comment]
this is a bug,also occurred，did you fix it？
