### ISSUE TITLE
Failed on Windows 8.1

### ISSUE THREAD

**Issue by Dgame** [aki77/atom-autocomplete-ctags#3]
I got this output:

```
Installing “autocomplete-ctags@0.3.1” failed.Hide output…

> runas@2.0.0 install C:\Users\Randy\AppData\Local\Temp\apm-install-dir-11572-4664-1kxu3rz\node_modules\autocomplete-ctags\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild


C:\Users\Randy\AppData\Local\Temp\apm-install-dir-11572-4664-1kxu3rz\node_modules\autocomplete-ctags\node_modules\pathwatcher\node_modules\runas>node "C:\Users\Randy\AppData\Local\atom\app-1.0.3\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

> ctags@2.1.0 install C:\Users\Randy\AppData\Local\Temp\apm-install-dir-11572-4664-1kxu3rz\node_modules\autocomplete-ctags\node_modules\ctags
> node-gyp rebuild


C:\Users\Randy\AppData\Local\Temp\apm-install-dir-11572-4664-1kxu3rz\node_modules\autocomplete-ctags\node_modules\ctags>node "C:\Users\Randy\AppData\Local\atom\app-1.0.3\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

gypgypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Randy\\AppData\\Local\\atom\\app-1.0.3\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\Randy\\AppData\\Local\\atom\\app-1.0.3\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Randy\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Randy\\.atom\\.apmrc" "install" "C:\\Users\\Randy\\AppData\\Local\\Temp\\d-11572-4664-1ktlntn\\package.tgz" "--target=0.22.0" "--arch=ia32"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! ctags@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ctags@2.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ctags package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ctags
npm ERR! There is likely additional logging output above.
```

**Comment by Dgame** [comment]
I tried to download the zip and drag & drop it manually but:

```
Failed to load the autocomplete-ctags package
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.3
**System**: RANDY
**Thrown From**: [autocomplete-ctags](https://github.com/aki77/atom-autocomplete-ctags) package, v0.3.1


### Stack Trace

Failed to load the autocomplete-ctags package

```

At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
  at Module._resolveFilename (module.js:328:15)
  at Function.exports.register.Module._resolveFilename (C:\Users\Randy\AppData\Local\atom\app-1.0.3\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Randy.atom\packages\atom-autocomplete-ctags\lib\tags-file.coffee:1:5)
  at Object.<anonymous> (C:\Users\Randy.atom\packages\atom-autocomplete-ctags\lib\tags-file.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\Randy\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Randy.atom\packages\atom-autocomplete-ctags\lib\ctags-provider.coffee:3:12)
  at Object.<anonymous> (C:\Users\Randy.atom\packages\atom-autocomplete-ctags\lib\ctags-provider.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\Randy\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Randy.atom\packages\atom-autocomplete-ctags\lib\main.coffee:1:17)
  at Object.<anonymous> (C:\Users\Randy.atom\packages\atom-autocomplete-ctags\lib\main.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\Randy\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\Randy\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:715:34)
  at C:\Users\Randy\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:190:28
  at Package.module.exports.Package.measure (C:\Users\Randy\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:167:15)
  at Package.module.exports.Package.load (C:\Users\Randy\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Randy\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package-manager.js:373:14)
  at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\Randy\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package-manager.js:337:14)
  at Atom.module.exports.Atom.startEditorWindow (C:\Users\Randy\AppData\Local\atom\app-1.0.3\resources\app.asar\src\atom.js:670:21)
  at Object.<anonymous> (C:\Users\Randy\AppData\Local\atom\app-1.0.3\resources\app.asar\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (C:\Users\Randy\AppData\Local\atom\app-1.0.3\resources\app.asar\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js](C:UsersRandyAppDataLocalatomapp-1.0.3resourcesapp.asarsrcbabel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///C:/Users/Randy/AppData/Local/atom/app-1.0.3/resources/app.asar/static/index.js:96:23)
  at window.onload (file:///C:/Users/Randy/AppData/Local/atom/app-1.0.3/resources/app.asar/static/index.js:36:7)

```

### Commands

```

``````

### Config

```json
{
  "core": {
    "disabledPackages": [
      "archive-view",
      "image-view",
      "language-clojure",
      "language-csharp",
      "language-java",
      "language-less",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-toml",
      "metrics",
      "autocomplete-clang",
      "linter-cpplint",
      "linter-phplint",
      "phplint",
      "linter-clang",
      "symbols-view",
      "php-analyser"
    ],
    "audioBeep": false,
    "themes": [
      "jonikorpi-atom-theme-ui",
      "solarized-dark-syntax"
    ]
  }
}
``````

### Installed Packages

``` coffee
# User
atom-ctags, v4.1.4
autocomplete-php, v0.3.6
ctags-status, v1.3.3
emmet, v2.3.12
jonikorpi-atom-theme-ui, v4.4.1
language-d, v3.2.1
linter, v1.2.4
linter-dscanner, v0.1.0
linter-php, v1.0.2
linter-phpmd, v1.0.0
minimap, v4.12.1
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.7
minimap-highlight-selected, v4.3.0
minimap-linter, v1.0.0
minimap-selection, v4.3.0
symbols-tree-view, v0.9.3
timecop, v0.31.0
zentabs, v0.8.6

# Dev
No dev packages
```

**Comment by Dgame** [comment]
It worked on my Laptop which uses also Win 8.1. Strange, I will investigate that. Have you any hints why this could happen or what exactly happens?

BTW:
Would your Plugin provides me a completion for this code snippet?

``` php
<?php

class Foo {
    /**
    * @var string
    */
    public $a_simple_var = '';
}


$f = new Foo();
$f->
```

I would expect `a_simple_var` after the `->` as code-completion suggestion. Does your Plugin provide that?

**Comment by Dgame** [comment]
I tried it with a fresh installation on my PC. Still the same error as in the first post.

**Comment by aki77** [comment]
problem of [node-ctags](https://github.com/atom/node-ctags). 
I don't know how to solve it. :cry: 

https://github.com/atom/node-ctags/issues/10

**Comment by Dgame** [comment]
Would your plugin smart enough to differ between types?

Example:

``` php
<?php

class Bar {
    /**
    */
    public $var_abc = null;
    public $var_xyz = null;
    public $var_foo = null;

    public function foourz() { }
}

class Foo {
    public function foobar($a) {
        return new Bar();
    }

    public function test() {

    }
}

$f = new Foo();
$f->foo
```

Would your plugin suggest only `foobar`or also `foourz`?

**Comment by n-prat** [comment]
I had the same issue (Win10 x64).
I fixed by manually installing node-ctags and atom-autocomplete-ctags :
- 1: install node-ctags with npm
- 2: install atom-autocomplete-ctags with apm

You have to check the python version being used(eg "python --version" and "where python"). I had multiple versions in my path.
Then force npm/node-gyp to use python 2.7 :   
- node-gyp --python /path/to/python2.7
  OR - npm config set python /path/to/executable/python2.7
  Personnally, I installed a python2 virtualenv with conda, and did the manual install from a cmd in it.
