### ISSUE TITLE
Unable to install on Atom 1.3.0-beta6

### ISSUE THREAD

**Issue by jyggen** [aki77/atom-autocomplete-ctags#6]
Hi.

I receive the following error when trying to install this plugin on Atom 1.3.0-beta6 (OS X 10.11):

```
> runas@3.1.1 install /private/var/folders/1_/j6pgbhz546g4t92sckw7215c0000gn/T/apm-install-dir-1151027-2236-b52gpr/node_modules/autocomplete-ctags/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild


> ctags@3.0.0 install /private/var/folders/1_/j6pgbhz546g4t92sckw7215c0000gn/T/apm-install-dir-1151027-2236-b52gpr/node_modules/autocomplete-ctags/node_modules/ctags
> node-gyp rebuild


make: *** No rule to make target `../../../../../../../../../../../../../../Applications/Atom', needed by `Makefile'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/1_/j6pgbhz546g4t92sckw7215c0000gn/T/apm-install-dir-1151027-2236-b52gpr/node_modules/autocomplete-ctags/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
make: *** No rule to make target `../../../../../../../../../../../../Applications/Atom', needed by `Makefile'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/1_/j6pgbhz546g4t92sckw7215c0000gn/T/apm-install-dir-1151027-2236-b52gpr/node_modules/autocomplete-ctags/node_modules/ctags
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.0.0
npm ERR! argv "/Applications/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/jyggen/.atom/.apm/.apmrc" "--userconfig" "/Users/jyggen/.atom/.apmrc" "install" "/private/var/folders/1_/j6pgbhz546g4t92sckw7215c0000gn/T/d-1151027-2236-1774c7r/package.tgz" "--target=0.34.3" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/1_/j6pgbhz546g4t92sckw7215c0000gn/T/apm-install-dir-1151027-2236-b52gpr/npm-debug.log
```

I'm aware that I'm using a beta version, but figured I'd give a heads up so it can be fixed before everyone and their dog upgrade to 1.3 :)

Cheers!

**Comment by aki77** [comment]
Please see #5.
