### ISSUE TITLE
fails to install in atom 1.3.2

### ISSUE THREAD

**Issue by gsparx** [aki77/atom-autocomplete-ctags#7]
I'm running into the following error trying to install autocomplete-ctags in Atom v 1.3.2 in Ubuntu 14.04

I'm able to install other packages (I'm currently using atom-ctags until I can get this issue figured out)

I tried reinstalling node, npm, and atom to no avail.  autocomplete-ctags was working fine as of about a week ago, but I decided to update the package, and it failed with the error.  I uninstalled autocomplete-ctags to see if I could clean-install the new version, but I'm seeing the same error.  Unfortunately that npm-debug log doesn't exist in the directory specified in the warning.

```
> runas@3.1.1 install /tmp/apm-install-dir-1151121-29493-g4dwll/node_modules/autocomplete-ctags/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

make: Entering directory `/tmp/apm-install-dir-1151121-29493-g4dwll/node_modules/autocomplete-ctags/node_modules/pathwatcher/node_modules/runas/build'
  CXX(target) Release/obj.target/runas/src/main.o
make: Leaving directory `/tmp/apm-install-dir-1151121-29493-g4dwll/node_modules/autocomplete-ctags/node_modules/pathwatcher/node_modules/runas/build'

> ctags@3.0.0 install /tmp/apm-install-dir-1151121-29493-g4dwll/node_modules/autocomplete-ctags/node_modules/ctags
> node-gyp rebuild

make: Entering directory `/tmp/apm-install-dir-1151121-29493-g4dwll/node_modules/autocomplete-ctags/node_modules/ctags/build'
  CC(target) Release/obj.target/ctags/src/readtags.o
  CXX(target) Release/obj.target/ctags/src/tags.o
  CXX(target) Release/obj.target/ctags/src/tag-finder.o
  CXX(target) Release/obj.target/ctags/src/tag-reader.o
  SOLINK_MODULE(target) Release/obj.target/ctags.node
  COPY Release/ctags.node
make: Leaving directory `/tmp/apm-install-dir-1151121-29493-g4dwll/node_modules/autocomplete-ctags/node_modules/ctags/build'

../src/main.cc:1:17: fatal error: nan.h: No such file or directory
 #include "nan.h"
                 ^
compilation terminated.
The bug is not reproducible, so it is likely a hardware or OS problem.
make: *** [Release/obj.target/runas/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.16.0-55-generic
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-1151121-29493-g4dwll/node_modules/autocomplete-ctags/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 3.16.0-55-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/garretts/.atom/.apm/.apmrc" "--userconfig" "/home/garretts/.atom/.apmrc" "install" "/tmp/d-1151121-29493-1j4hb1d/package.tgz" "--target=0.34.3" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-1151121-29493-g4dwll/npm-debug.log
```

**Comment by aki77** [comment]
similar issue
https://github.com/mulesoft/api-workbench/issues/25

**Comment by gsparx** [comment]
Looks like their solution was to remove some native dependencies which were causing issues.  Per this log, it looks like it's blowing up trying to build ctags.  I'm using ripper-tags to generate ctags externally for my ruby application.  Is there a possibility you could remove the ctags dependency?  Or is that what is actually used for the tag traversal?

**Comment by aki77** [comment]
Use the [node-ctags](https://github.com/atom/node-ctags) for the parse of the tags file.
