### ISSUE TITLE
Failed to activate the autocomplete-ctags package

### ISSUE THREAD

**Issue by SuctorialBog** [aki77/atom-autocomplete-ctags#9]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.2
**System**: Mac OS X 10.11.3
**Thrown From**: [autocomplete-ctags](https://github.com/aki77/atom-autocomplete-ctags) package, v0.4.0
### Stack Trace

Failed to activate the autocomplete-ctags package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/skytown/.atom/packages/autocomplete-ctags/lib/tags-file.coffee:1:5)
    at Object.<anonymous> (/Users/skytown/.atom/packages/autocomplete-ctags/lib/tags-file.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/skytown/.atom/packages/autocomplete-ctags/lib/ctags-provider.coffee:3:12)
    at Object.<anonymous> (/Users/skytown/.atom/packages/autocomplete-ctags/lib/ctags-provider.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/skytown/.atom/packages/autocomplete-ctags/lib/main.coffee:1:17)
    at Object.<anonymous> (/Users/skytown/.atom/packages/autocomplete-ctags/lib/main.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:722:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:505:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:500:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:483:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-js-specs",
      "language-js-specs",
      "language-js-specs",
      "close-tags",
      "jsonlint",
      "linter-flow",
      "linter-haml",
      "linter-js-standard",
      "linter-scss-lint",
      "linter"
    ],
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "flatland-dark-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
auto-indent, v0.5.0
autoclose-html, v0.20.0
autocomplete-ctags, v0.4.0
autocomplete-paths, v1.0.2
color-picker, v2.1.1
flatland-dark-ui, v0.2.4
indent-guide-improved, v1.4.5
javascript-snippets, v1.2.0
language-SCSS, v0.4.0
language-javascript-better, v1.7.1
language-javascript-jsx, v0.3.7
language-javascript-semantic, v0.2.1
monokai, v0.18.0
pigments, v0.23.0

# Dev
No dev packages
```

**Comment by aki77** [comment]
I can't reproduce the error.
Please try re-install.

```
apm uninstall autocomplete-ctags
apm install autocomplete-ctags
```
